[package]
name = "pixel-sahur/pixel-sahur"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
React = "jsdotlua/react@17.1.0"
ReactRoblox = "jsdotlua/react-roblox@17.1.0"
ByteNet = "ffrostflame/bytenet@0.4.1"
